import { ReactNode } from "react";
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import Link from 'next/link'
import './globals.css'

const inter = Inter({subsets: [ 'latin' ]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
  
  return (
    <html lang="en">
    <body className={inter.className}>
    <nav>
      <ul>
        <li>
          <Link href="/">
            Home
          </Link>
        </li>
        <li>
          <Link href="/dashboard">
            Dashboard
          </Link>
        </li>
      </ul>
    </nav>
    {children}
    </body>
    </html>
  )
}
